# Generated by Django 3.1.2 on 2020-11-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='confession',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
