# Generated by Django 3.1.2 on 2020-11-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201109_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('', 'Unknow')], max_length=1),
        ),
    ]
